const productos = [
    {
        IDProducto:1,
        descripcion:"yyy",
        rubro:"gg",
        precio:43343,
        URLImagen:"",
    },
    {
        IDProducto:2,
        descripcion:"yyy",
        rubro:"gg",
        precio:43343,
        URLImagen:"",
    },
    {
        IDProducto:3,
        descripcion:"yyy",
        rubro:"gg",
        precio:43343,
        URLImagen:"",
    },
    {
        IDProducto:4,
        descripcion:"yyy",
        rubro:"gg",
        precio:43343,
        URLImagen:"",
    }
]